export const MAX_SUPER_ADMINS = 2;

export const SUPER_ADMIN_ENV_EMAIL_KEYS = [
  "SUPER_ADMIN_EMAIL",
  "SUPER_ADMIN_EMAIL_1",
  "ADMIN_EMAIL",
];

export const SUPER_ADMIN_ENV_PASSWORD_KEYS = [
  "SUPER_ADMIN_PASSWORD",
  "SUPER_ADMIN_PASSWORD_1",
  "ADMIN_PASSWORD",
];
