name: Deploy Backend (API)

on:
  push:
    branches:
      - Master
      - dev
    paths:
      - "server/**"

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'Master' && 'production' || 'development' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set environment
        run: |
          if [[ "${GITHUB_REF_NAME}" == "Master" ]]; then
            echo "SERVER_HOST=${{ vars.PROD_SERVER_HOST }}" >> $GITHUB_ENV
            echo "SERVER_USER=${{ vars.PROD_SERVER_USER }}" >> $GITHUB_ENV
            echo "API_DIR=/home/${{ vars.PROD_SERVER_USER }}/alaba-marketplace-production/server" >> $GITHUB_ENV
            echo "API_NAME=alabamarketplace-apis" >> $GITHUB_ENV
            echo "SSH_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.PROD_SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "SERVER_HOST=${{ vars.DEV_SERVER_HOST }}" >> $GITHUB_ENV
            echo "SERVER_USER=${{ vars.DEV_SERVER_USER }}" >> $GITHUB_ENV
            echo "API_DIR=/home/${{ vars.DEV_SERVER_USER }}/alaba-marketplace/server" >> $GITHUB_ENV
            echo "API_NAME=alabamarketplace-backend" >> $GITHUB_ENV
            echo "SSH_KEY<<EOF" >> $GITHUB_ENV
            echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          fi

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

      - name: Deploy backend
        run: |
          ssh $SERVER_USER@$SERVER_HOST << EOF
            set -e
            cd $API_DIR

            npm install
            npm run build

            PM2="\$HOME/.nvm/versions/node/v20.19.6/bin/pm2"

            if [[ "${GITHUB_REF_NAME}" == "Master" ]]; then
              \$PM2 reload dist/main.js --name $API_NAME --node-args="-r dotenv/config"
            else
              \$PM2 reload ecosystem.config.js --only $API_NAME || \
              \$PM2 start ecosystem.config.js
            fi

            \$PM2 save
          EOF
